### ISSUE TITLE
等待自己能量球问题反馈

### ISSUE THREAD

**Issue by thumike** [e1399579/autojs#10]
感谢作者的及时更新，4月12日更新的版本使用过程中遇到一点点小问题，已经找出原因，特反馈给您。
1. 第481行  forest.find(descMatches(/^(收集能量|\d+k?g|绿色能量)$/)).forEach(function (o) 
   这里似乎应该只保留descMatches(/^(收集能量)$/)否则会点到右上角自己能量值里面，然后出不来。今天 
   早上没有成功收到自己能量(笑哭)。

2. this.takeRemain 函数里面，建议增加执行条件 if(list.length>0) ,否则即使没有能量球，也会一直处于检测中。其中for (var i = 0;i <= millisecond;i += step_time + 156))建议改为for (var i = 0;i <= millisecond;i += step_time + 156*list.length))，因为若有多个能量球，则需要点击多次，延时增加。(今天早上发现的)

3. 582-583行， 我测试的时候会卡在好友能量界面,
        var cover;
        if (cover = descMatches(/\d{2}:\d{2}:\d{2}/).findOnce()) 
   我自己改为:
        var cover＝descMatches(/\d{2}:\d{2}:\d{2}/);
        if (cover.exists()) 
   后，测试正常，不知道是不是个例。
——————————————————————————
为了反馈，特意去注册github帐号，结果发现我已经注册过了，又去找回密码，再来反馈。
总之，感谢作者！希望一直保持更新哦～

祝好！

**Comment by SuperMonster003** [comment]
😄
很棒
第三点解决了不点击能量球的问题 但还是觉得有些奇怪 会出现"还有x分钟才能收取哦"这样的提示
另外第三点代码中的两个等于符号 第一个是半角 而第二个是全角的

**Comment by SuperMonster003** [comment]
1. 意思是说 进入蚂蚁森林后 右上角自己头像右侧的能量值 也会被看作是一个能量球吗 因为我发现默认情况下如果当前时间在设置的检测时间范围内 且自己的总能量球数量为0时 脚本是会点击右上角进入种树界面的
>          而且在只有一个能量球的情况下，会误算作两个，所以检测结束时间也会变长。
>          -- from thumike @ Apr 13, 2018, 7:20 PM GMT+8
2. 检测时间变长 没错 确实不如以前快了 以前进入好友森林之后马上就会收取能量 现在要停顿一下才收取
3. "还有x分钟才能收取哦"
我说的不是当前时间在设置时间范围内时收取自己能量的提示 而是收取好友能量时 例如有一个可收取能量球 (如262g) 同时 还有一个倒计时能量球 (如01:34) 这个时候脚本会点击可收取能量球 (262g) 但还会点击一下那个倒计时能量球 (01:34) 提示说"还有1时34分才能收取哦"

**Comment by SuperMonster003** [comment]
@thumike 
👌 😃

**Comment by e1399579** [comment]
1，2已经修复。3请更新安装包，https://pan.baidu.com/s/1i6KBbnv
