### ISSUE TITLE
提示缺少图片文件，或无法收取好友能量

### ISSUE THREAD

**Issue by Diziou** [e1399579/autojs#12]
提示缺少图片文件，或无法收取好友能量，目录文件下有“take.png”,也尝试过自己截图均未成功

**Comment by SuperMonster003** [comment]
请尝试在内部存储根目录下建立名为"脚本"的文件夹 (若为英文系统 则文件夹命名为"Scripts")
然后把包含"take.png"文件在内的所有项目文件 放在此目录下
打开"Auto.js"软件 在"脚本"标签刷新 应该可以看到所有JS脚本

_内部存储的目录路径样例_
_1. "/storage/emulated/0/"
2. "/sdcard/"
3. "/mnt/sdcard"
4. "/mnt/user/0/primary"_

**Comment by e1399579** [comment]
@Diziou 查看一下日志，确保日志里面的路径（当前执行路径）与图片路径一致

**Comment by Diziou** [comment]
更新后依旧无法收取好友能量

**Comment by SuperMonster003** [comment]
@Diziou
Auto.js软件的版本是3.1.1 Alpha5以上吗

**Comment by Diziou** [comment]
不是 3.1.0 beta 吗？

**Comment by SuperMonster003** [comment]
@Diziou 
是的 需要更新Auto.js
https://pan.baidu.com/s/1i6KBbnv
这里有新版

**Comment by Diziou** [comment]
可以了，谢谢👍

**Comment by SuperMonster003** [comment]
@Diziou 
😋
