### ISSUE TITLE
无法收取好友能量

### ISSUE THREAD

**Issue by Diziou** [e1399579/autojs#18]
好像昨天开始无法收取好友的能量，能检测收取并进入好友主页，但是无法收取

**Comment by SuperMonster003** [comment]
我在支付宝最新版10.1.20.568遇到过此问题
可尝试退回支付宝10.1.18.708版本
PS: 最新版支付宝清空数据后可暂时解决问题 但过一段时间就不行了 我最近一直在用10.1.18.707版本 两个手机均未出现此问题

**Comment by Diziou** [comment]
如果有未成熟的能量，有时会一直点击并提示多长时间后可收取，无法进入下一步收取好友能量，有时会正常

**Comment by SuperMonster003** [comment]
看看config.js里面的时间段设置 如7:00-7:20 在这个时间范围内进入蚂蚁森林主页的话 会一直点击自己所有能量球的

**Comment by Diziou** [comment]
这样啊，好的谢谢啦😀
