### ISSUE TITLE
2K屏无法使用

### ISSUE THREAD

**Issue by xuchjian** [e1399579/autojs#19]
支付宝：10.1.18；
auto.js版本：3.1.1alpha5；
运行进入到森林以后，也是如下错误：
TypeError: Cannot call method "parent" of null (<蚂蚁森林>#461)
at script(<蚂蚁森林>:461)
at script(<蚂蚁森林>:261)
at script.start(<蚂蚁森林>:96)
at script(<蚂蚁森林>:21)
手机是pixel xl，在2K分辨率下无法运行，出现上述代码
修改分辨率后1920 可以运行，但是无法点中好友和收取能量，总有偏差，不知道该如何修改

**Comment by SuperMonster003** [comment]
把Auto.js升级到alpha7试试看

**Comment by xuchjian** [comment]
大神你好，已经把Auto.js升级到alpha7，还是出现在461的错误上

**Comment by SuperMonster003** [comment]
抱歉啊 我也不知道怎么解决
:frowning::sweat_smile:
手头上的手机全都是1280×720的 嗯 找到一个好的借口 哈哈
:flushed::grin:
另外我不是大神哦
:moyai::wink:

**Comment by xuchjian** [comment]
另外我想问下，tasker里面 目标对于broadcast receiver，activity，service选择哪一个？？
