### ISSUE TITLE
非标准分辨率的怎么截图呢？

### ISSUE THREAD

**Issue by JamesLebron** [e1399579/autojs#27]
作者你好，我的手机是小米8，不是标准分辨率2248*1080
我试着在手机上截图之后，发至电脑，使用QQ截取 小手 区域，放置到对应目录。
脚本能正常运行，但是似乎没检测到小手区域。一直在列表循环，没有点击进去。

**Comment by e1399579** [comment]
使用windows画图工具编辑，注意不要让小手变形，且截图略小于小手范围
