### ISSUE TITLE
Xposed edge pro定时任务中， shell命令执行时没反应？

### ISSUE THREAD

**Issue by huxingui** [e1399579/autojs#29]
命令如下：
am start -n com.stardust.scriptdroid/.external.open.RunIntentActivity -d file:///storage/emulated/0/脚本/e1399579/蚂蚁森林.js  -t text/javascript

**Comment by DanielEcho** [comment]
因为新版的autojs换了包名

**Comment by huxingui** [comment]
还有 蚂蚁森林.js  能翻到好友列表，却不会收取。谁能告诉我怎么改才能完美地运行，我是小白，不懂啊。

**Comment by huxingui** [comment]
@DanielEcho怎么改？
