### ISSUE TITLE
第一次运行收了自己能量后，就再也没反应了！

### ISSUE THREAD

**Issue by zwjdujin** [e1399579/autojs#31]
第一次运行蚂蚁森林，还能收取自己能量。后面再运行脚本，就没有任何反应了。这是怎么回事？

**Comment by zwjdujin** [comment]
任务日志如下！
![20180806085947](https://user-images.githubusercontent.com/25227970/43692123-3173db7c-9957-11e8-8344-c901efa7d4c2.jpg)

**Comment by zwjdujin** [comment]
我的路径貌似没有0，这是怎么回事？

**Comment by e1399579** [comment]
更新一下Secure.js，这是bug

**Comment by zwjdujin** [comment]
@e1399579 已在两三天前更新，感谢大大回复！
