### ISSUE TITLE
米8运行蚂蚁森林报错

### ISSUE THREAD

**Issue by PolymerLiu** [e1399579/autojs#36]
cannot find function all in object[object Object] (<蚂蚁森林>#95)

**Comment by e1399579** [comment]
这是Auto.js软件的问题，反馈给作者吧。
PS:你Auto.js用的是4.0版本吗？

**Comment by PolymerLiu** [comment]
现在升级到4.0可以了

**Comment by e1399579** [comment]
https://www.coolapk.com/apk/org.autojs.autojs
