### ISSUE TITLE
Timeout value设不到3600啊

### ISSUE THREAD

**Issue by dust2k** [e1399579/autojs#37]
![img_20180818_161424](https://user-images.githubusercontent.com/22682685/44297314-d34af580-a301-11e8-823c-d73c5ff6da8c.jpg)
增加执行一次tasker的时候，第四步要求设timeout 3600，但tasker界面上只给设置最大到50

**Comment by e1399579** [comment]
![image](https://user-images.githubusercontent.com/4549943/44307785-61df7580-a3db-11e8-9de9-144f0985a160.png)
见右边那个图标

不知道你用的哪个版本，我是在酷安下载的，5.0u7

**Comment by dust2k** [comment]
我的也是酷安下的
![img_20180821_001728](https://user-images.githubusercontent.com/22682685/44352759-c67ffa80-a4d7-11e8-8d2c-ee71eef7cb82.jpg)
