### ISSUE TITLE
蚂蚁森林收取自己能量的问题

### ISSUE THREAD

**Issue by zwjdujin** [e1399579/autojs#38]
假设蚂蚁森林自己的能量在7:15生成，并在参数中设置“7:14-7:16”，而我在7:10就开始运行脚本，收取他人能量，能否在“7:14-7:16”的时候返回自己的界面秒收能量？

目前的状况是我每天7:10的时候运行脚本，等我7:20强制关闭重新运行脚本时，自己的能量已经被偷完了……

**Comment by e1399579** [comment]
很简单，如果7:10定时那次没有办法在7:15之前完成运行，那就放弃此次定时，改为7:15执行。毕竟自己的能量比较多
PS：执行时间太长了吧，我500好友最多也只需要3分钟左右

**Comment by zwjdujin** [comment]
@e1399579 哇，500好友3分钟？我600+好友需要在早晨7点-8点左右才能收完！
主要是我7:10-20之间要开车，所以就在7:10执行了。

**Comment by e1399579** [comment]
是不是太多好友加了保护罩？我都把他们清了:)

**Comment by zwjdujin** [comment]
@e1399579 几乎没人用防护罩，但是点开小手到收取能量得好几秒钟吧！而早晨7点-8点的时候刚好又是能量生成的时候，所以一轮下来，没个二三十、三四十分钟是不可能的。
