### ISSUE TITLE
Bug反馈: 偶尔无法点击列表中的好友

### ISSUE THREAD

**Issue by SuperMonster003** [e1399579/autojs#4]
当好友列表最底部好友能量可收取 且屏幕位置较特殊时 会出现无法点击的情况
截图案例如下

![screenshot_20180318-202223_1](https://user-images.githubusercontent.com/30370009/37565988-fdc04842-2aed-11e8-8bda-aeb94fea0045.png)

超时后提示无法进入好友森林 返回(Back)一次后 脚本会继续不停上滑(Swipe)屏幕 直到手动停止

_Sony Xperia XZ1 Compact (G8441)_
_720×1280 (0px navigation bar)_
_Android 8.0 (47.1.A.12.75)_

**Comment by e1399579** [comment]
有时点击不成功，后面的逻辑全乱了，现在的版本有个最大滑动次数，可以防止死循环
