### ISSUE TITLE
能量还是不行

### ISSUE THREAD

**Issue by wyfang** [e1399579/autojs#49]
之前Nexus手机，全部不行。

这次换了一台手机，锤子手机，微信运动和小鸡的星星球都勉强可以运行，微信运动就是点赞一半一半，小鸡就是只能打几个就掉了，但至少可以运行一小火。

蚂蚁森林就不行，运行一瞬间就提示一些东西，还在auto js界面。这是截图：
![screenshot_2018-09-20-07-59-02-901](https://user-images.githubusercontent.com/17900420/45788161-77321300-bcab-11e8-9f4f-fd76943d7c98.png)

**Comment by e1399579** [comment]
更新下Auto.js软件试试，https://pan.baidu.com/s/1i6KBbnv

**Comment by wyfang** [comment]
> 更新下Auto.js软件试试，https://pan.baidu.com/s/1i6KBbnv

可以！我有个疑问，这个程序获取截图，只是在内存里截图识别区域？还是是真截图，保存在闪存上？长期运行会不会伤手机？

**Comment by e1399579** [comment]
@wyfang 会不会伤手机我不知道，是在内存里面识别的，并没有把截图保存到手机里面

**Comment by wyfang** [comment]
@e1399579 还有个问题，不是默认配置是有5分钟内的能量，会一直上下滑动等待检测吗？我昨天可以，今天怎么失效了，很多剩余低于5分钟，直接就返回auto js了

**Comment by e1399579** [comment]
来回检测是在定时收取自己能量的时间段之后才会生效，以免来回执行时间过长导致无法收取自己的能量，毕竟自己的能量多
