### ISSUE TITLE
无法运行脚本

### ISSUE THREAD

**Issue by NeoFantom** [e1399579/autojs#55]

**Comment by NeoFantom** [comment]
我的手机是一加3，下载了最新版Auto.js软件，所有文件全部放在emulated/0/脚本文件夹下，也尝试过其他文件夹。不论是仅导入 蚂蚁森林.js 和 蚂蚁森林设置向导.js，还是导入要求的所有文件，都没有用。

**Comment by e1399579** [comment]
具体是什么现象？发下日志

**Comment by sian0** [comment]
17:42:37.255/D: 即将收取能量，按音量上键停止
17:42:37.588/D: { isScreenOn: true,
  currentPackage: 'com.stardust.scriptdroid',
  isRunning: 3,
  version: '10.1.38.2139' }
17:42:37.596/E: TypeError: Cannot find function all in object [object Object]. (<蚂蚁森林>#95)
	at script(<蚂蚁森林>:95)
	at script(<蚂蚁森林>:89)
	at script.start(<蚂蚁森林>:42)
	at script(<蚂蚁森林>:21)
17:42:37.597/V: \n------------\n[/storage/emulated/0/Scripts/能量/蚂蚁森林.js]Finished，spent 0.375000 seconds.
17:42:49.861/V: Running[/storage/emulated/0/Scripts/能量/蚂蚁森林设置向导.js]
17:42:54.674/V: \n------------\n[/storage/emulated/0/Scripts/能量/蚂蚁森林设置向导.js]Finished，spent 4.813000 seconds.
17:42:56.387/V: Running[/storage/emulated/0/Scripts/能量/蚂蚁森林.js]
17:42:56.403/D: 即将收取能量，按音量上键停止
17:42:56.660/D: { isScreenOn: true,
  currentPackage: 'com.stardust.scriptdroid',
  isRunning: 3,
  version: '10.1.38.2139' }
17:42:56.674/E: TypeError: Cannot find function all in object [object Object]. (<蚂蚁森林>#95)
	at script(<蚂蚁森林>:95)
	at script(<蚂蚁森林>:89)
	at script.start(<蚂蚁森林>:42)
	at script(<蚂蚁森林>:21)

**Comment by SuperMonster003** [comment]
报错是说没有识别engines模块的all方法
不是缺少文件的问题
确定Autojs是最新版吗
目前最新版为4.0.4 alpha7

**Comment by NeoFantom** [comment]
我当时没有引入全部文件。是自己操作失误。

**Comment by Zhenyufdsa** [comment]
> 17:42:37.255/D: 即将收取能量，按音量上键停止
> 17:42:37.588/D: { isScreenOn: true,
> currentPackage: 'com.stardust.scriptdroid',
> isRunning: 3,
> version: '10.1.38.2139' }
> 17:42:37.596/E: TypeError: Cannot find function all in object [object Object]. (<蚂蚁森林>#95)
> at script(<蚂蚁森林>:95)
> at script(<蚂蚁森林>:89)
> at script.start(<蚂蚁森林>:42)
> at script(<蚂蚁森林>:21)
> 17:42:37.597/V: \n------------\n[/storage/emulated/0/Scripts/能量/蚂蚁森林.js]Finished，spent 0.375000 seconds.
> 17:42:49.861/V: Running[/storage/emulated/0/Scripts/能量/蚂蚁森林设置向导.js]
> 17:42:54.674/V: \n------------\n[/storage/emulated/0/Scripts/能量/蚂蚁森林设置向导.js]Finished，spent 4.813000 seconds.
> 17:42:56.387/V: Running[/storage/emulated/0/Scripts/能量/蚂蚁森林.js]
> 17:42:56.403/D: 即将收取能量，按音量上键停止
> 17:42:56.660/D: { isScreenOn: true,
> currentPackage: 'com.stardust.scriptdroid',
> isRunning: 3,
> version: '10.1.38.2139' }
> 17:42:56.674/E: TypeError: Cannot find function all in object [object Object]. (<蚂蚁森林>#95)
> at script(<蚂蚁森林>:95)
> at script(<蚂蚁森林>:89)
> at script.start(<蚂蚁森林>:42)
> at script(<蚂蚁森林>:21)

想问问你后来是怎么解决的啊？
