### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by sian0** [e1399579/autojs#56]
17:42:37.255/D: 即将收取能量，按音量上键停止
17:42:37.588/D: { isScreenOn: true,
  currentPackage: 'com.stardust.scriptdroid',
  isRunning: 3,
  version: '10.1.38.2139' }
17:42:37.596/E: TypeError: Cannot find function all in object [object Object]. (<蚂蚁森林>#95)
	at script(<蚂蚁森林>:95)
	at script(<蚂蚁森林>:89)
	at script.start(<蚂蚁森林>:42)
	at script(<蚂蚁森林>:21)
17:42:37.597/V: \n------------\n[/storage/emulated/0/Scripts/能量/蚂蚁森林.js]Finished，spent 0.375000 seconds.
17:42:49.861/V: Running[/storage/emulated/0/Scripts/能量/蚂蚁森林设置向导.js]
17:42:54.674/V: \n------------\n[/storage/emulated/0/Scripts/能量/蚂蚁森林设置向导.js]Finished，spent 4.813000 seconds.
17:42:56.387/V: Running[/storage/emulated/0/Scripts/能量/蚂蚁森林.js]
17:42:56.403/D: 即将收取能量，按音量上键停止
17:42:56.660/D: { isScreenOn: true,
  currentPackage: 'com.stardust.scriptdroid',
  isRunning: 3,
  version: '10.1.38.2139' }
17:42:56.674/E: TypeError: Cannot find function all in object [object Object]. (<蚂蚁森林>#95)
	at script(<蚂蚁森林>:95)
	at script(<蚂蚁森林>:89)
	at script.start(<蚂蚁森林>:42)
	at script(<蚂蚁森林>:21)

**Comment by e1399579** [comment]
仔细看使用说明，软件要求4.0以上。而且有人问了
