### ISSUE TITLE
蚂蚁森林坑爹的"新年礼"

### ISSUE THREAD

**Issue by SuperMonster003** [e1399579/autojs#66]
新年礼的按钮符合蚂蚁森林能量球的特征
因此会在进入森林后点击"新年礼"按钮
可通过筛选bounds的方式解决此问题

498行
`return (null !== desc.match(/^收集能量|^\s?$/));`
修改为
`return (null !== desc.match(/^收集能量|^\s?$/) && o.bounds().bottom > 300 * HEIGHT / 1280);`

**Comment by wyfang** [comment]
赞！对于我这种不是码农的人，这教程非常实用
